################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "Blog about Microsoft 365, SharePoint and the PnP Modern Search"
# copyright
copyright = "Copyright Franck Cornu @ 2022"