############### English navigation ################

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "PnP Modern Search"
url = "categories/modern-search"
weight = 2

[[main]]
name = "About"
url = "about"
weight = 3

# footer menu
[[footer]]
name = "About"
url = "about"
weight = 1